#

"""
Convert between base 10 integers and a alphanumberic base using 4-Letter or 5-Letter common male and female first names
Name source is US Census data
4-Letter encoding uses selected names from ~400 most common names, with problematic ones removed.
    Filtered names are intended to be easier to recite if needed.
5-Letter encoding 1127 names with NO filtering.
Order of names have been randomized.
"""

__version__ = '1.0'

class NameBaseConverter(object):
    DECIMAL_BASE_DIGITS = '0123456789'
    # Names taken from top four letter USA census names, Male+Female randomized
    NAME_BASE_DIGITS = tuple()
    NAME_BASE_DIGITS4 = tuple("NETA BURT GIGI JADE ZORA ZANE KACY LORE RONA LADY BART LONI JOSH LARA BURL LUCY KARY ASHA MACY SETH NONA MARX NERY TOYA KATI RAUL TESS BRAD ZENA YONG REED RUDY KORY IRMA JOHN NEDA MAIA JEFF COLE SONG DOUG TARA LINN STAN DORI HONG JONA DONA JERI WAVA MISS ERIC LEAH STAR TAMA ROSE TREY GAIL MAUD RICH SHAD ANYA DICK ZULA KAYE LINA ERIN KARA CHAS KALI EDDY TORY IVEY VIKI LALA ETTA JANE MACK ALVA LYLA TYRA ELVA MARA JANA YING ELKE ERYN ERIK DYAN VETA AIDA YOKO ISIS SHEA TERA LYLE CHAD EMMY NEVA MARK LING TODD FRAN GALE ZACK ERMA BRET OLIN ARLA EDEN LYNN LONA LEON EVAN NEIL ALEC NORA PURA LACI DANE TINA REBA KERI CHIN HUEY GREG GINO MARY WADE LOLA SARI OLGA MUOI RYAN BIBI CORA HUGO ASIA VERN CARI ANNE NANA ETHA SCOT ILDA ELIZ NOEL VIDA BREE FAYE KRIS RETA AMOS AIDE HYON ELMO DIAN KACI MARC MIKA JUNE RUSS KERA CARY SOOK OMER GLEN DEON BONG HYUN ELDA ZONA DARA DONG NOLA DUNG CLEO LINO MILO OREN ALDO NITA HUNG BELL KURT RORY SENA REID MIKI HOPE VITA SHON LERA RUTH YANG HANS DREW LULA NOVA AURA DALE DAWN BARB PAUL LUNA ELLY YUNG ZINA GENE CHUN THAD CURT TONA LANE KATE LILI TARI PETE RANA RENA EDDA BUCK WARD LILY JUAN ADAM ABEL TUAN EMMA ARIE JOSE LUPE JOEL HANK BILL VITO TAMI TOBY META NYLA NICK JESS NENA CRUZ ELSA OTTO ANNA LURA JANN ANDY ELSE KYLA IONA SUNG DELL JAYE RISA SKYE RUBY JACK HERB ECHO XUAN LUCI EVON ROSY HEDY MYRA DEBI ADAN ESTA RUBI OWEN GINA JAME ODIS ALIX ALLA LACY ROLF RITA KYRA MATT MOSE EUNA LEIA AVIS TRAN JOAN RENE GENA MANA BESS EMIL MIMI JAMI LORA ALMA LUIS BEAU VADA SEAN KARL DION EDNA CHAN EZRA JUDE CARA LOYD ELNA ROXY OTIS BERT EDIE ZITA MILA REDA ALAN CORY CODY LENA ALIA JOYE NIKI MINA TOMI PHIL JENE NEAL LIDA HANA SUZY RICK RINA JUDY NELL GERI LEIF JOEY MONA NADA DAVE SUZI FAWN EVIE CHET FERN LANA ROSS WILL TENA ELMA NGOC LULU LUKE LOAN JILL NOAH NIDA SOON TINY YUKO SANG JAKE ENID LIZA LYDA TROY OTHA BOYD CHAU JADA CHER SHAY DINA YURI ROMA KALA JODY CLAY RAYE NOMA SARA CARL BETH MAYE ROSA OPAL HANG LISA LEAN TANA MERI VIVA GARY EARL JONE REVA KING EXIE JEAN HOYT MING HANH ZOLA DINO JINA NINA KYLE JUNG KENA ARON TOBI ALEX IRIS SIMA ELLA VENA ROBT SAUL LOMA DENA NILA KENT TONY ELOY LEDA MICA RONI JENI VERA KIRK PAGE DANA IVAN LORY LEVI LONG SHAE LISE JULE LOIS INES THEO ABBY GWYN MIKE FRED RICO RIVA MAYA OLEN DEAN ALDA VEDA ELZA DORA HUGH KATY KIRA GWEN JENA DIRK OMAR".split())
    NAME_BASE_DIGITS5 = tuple("LEOLA AIMEE ROYAL ELIDA TERRY KATIA ALINA AGNES TONJA LINDY SOFIA LUCIO BLAKE CARLA CHUNG HILDA DIONE TERRI NISHA WILLA DELIA NEELY ALYCE ALEXA MARGY AMIRA TALIA MERCY CHONG GERRI ALETA BRYNN BUENA LIDIA MARNI LYNDA EDDIE PETRA MYONG KARLY TESHA OSCAR DEANN TRINH NEOMA KOREY DODIE ALYSA NIDIA KACEY NADIA TRACY LAINE ARDEN TRANG JAMEL HOLLI AMBER BRENT MERRY VICKY VIVAN MONTY GAYLE ALTON VINCE BELEN TRENT MERLE ELLAN EDYTH LOYCE ELROY VELVA KENDA EMIKO ANDRE EMELY KEITH CHRIS LEIGH MALKA SHILA LUISA AARON KAREN BRAIN LENNA MYUNG CLORA NELIA OLLIE YAEKO MANDI ELENI CASIE TAMMI MAREN ERIKA BAMBI RANDA KASEY ADELA ONITA JOANE DONNY BRYCE BELLA FAITH DUSTI TIARA MARGE ELYSE LONNY GENNA BYRON HILMA RANDY DARCI BRUNA JONIE KITTY VALDA BILLI MOIRA MANIE LOREN BRIAN MIKEL NINFA THEDA TIERA DARYL BENNY LAYNE TOBIE CARLY IRINA RANEE JENEE NICKY VANNA RANDI ISIAH CARRI HONEY ABRAM RANAE SHAUN SHENA MYRTA LUDIE CLARA LYNNA ETHAN ZAIDA TONDA LESIA MIRTA DETRA KIZZY CYRIL DARCY SHYLA CAMIE INGER SUZIE CARIN RUBYE AYANA ARIEL OUIDA VERLA MAIRE RENDA LEANN BELLE ERICK BLAIR KACIE KYOKO DAYLE KIERA BEULA KIANA ENOCH JAROD LUCAS FAIRY BELVA MAYRA MARLA JARED JORGE ARLEN AHMAD DOTTY ROBYN HARRY LEONE HERMA QUEEN DEVIN LEILA CARMA RETHA AUDRA JUANA LILLY SHARA DULCE MERRI MAURA ROMAN EDITH HEIKE NILSA DEREK AUDIE MAPLE BECKY JANIS MELBA ERICH QUINN GILDA JENAE NYDIA SEEMA KAREY JOYCE WALDO KEENA TWYLA TWANA MONET TYLER POLLY HELGA DIANN AVRIL HEIDE VELMA WILLY VANIA AMINA DENNA DAMON KENYA VIOLA GILMA BETTE VICKI ADDIE LIANA SABRA LIANE ERWIN LAURI LUCIE ANNIE CELSA SALLY DENAE LEORA ORPHA LLOYD DARON VANDA HOMER TYSON SHERI TRINA MAILE DAYSI TITUS DEANA JANEE LILIA ALPHA TANIA KIETH ISSAC WILDA NICKI FIONA DANIA DAGNY HULDA TAWNY LAVON REINA ARTIE EBONI KASIE GRETA KARMA MINDI DAVIS DEENA HEIDI ODELL MISTY MARTA DANAE TELMA DENNY CANDI NELDA MAUDE HALEY MINTA TANNA HEIDY WAYNE ORVAL LAREE RAYNA PETER MICKI EBONY TONIE CINDA TANYA MAYME KISHA XENIA GARRY PATTI LEOTA ALIZA ALANE KAILA ALANA GRACE FELIX JEWEL MAGAN TYRON JAIME ALLIE BOBBI LOUIS ERNIE DONTE TYREE JESSI BROOK FLETA TONIA MARLO KELLE RETTA COLIN NORMA JAMIE JULES MAURO MARTH JOANN TAMRA RIKKI ZELDA ADENA CARYL KARYL PERCY MYRON ETHEL JANEY TAYNA EHTEL DAINA ENOLA PILAR BRICE MARIE CAREY JESSE NOBLE VERDA DAISY SAMMY DEDRA DONNA KARIN SONYA REITA CHING TRUDY SHANA SHARI ELANE ROSIO AUREA ILONA ALTHA ANGEL TIANA KATIE JODIE DORIA LOURA RICKI JULIO CARIE SUNNI CLIFF ROCKY VERNA KATHE BERNA DUSTY DAVID REIKO AZZIE FLOYD DOYLE JENNI GAYLA ELLEN PEGGY TREVA LECIA ALIDA DWANA KELSI JANAE LAURA BOBBY LAMAR GARTH LEWIS MADIE GRANT BARRY ISELA LELIA TOMAS GERRY KERRY LARAE ASLEY MADGE ALLAN PENNY DORIE MISTI RAISA QIANA SILVA KARYN CLARK LATIA LONNA LEIDA ELLIS LUISE BOYCE ALICA JOHNA LIBBY LETHA JOVAN IVANA SILAS ROBIN SADYE TONEY ELISA LORIS CINDY ALISE TWILA CORAL NIKKI MILAN LUIGI KEELY MYRLE LOIDA JERRI BASIL TORIE SYBLE MISSY COLBY TAREN KEVEN MABLE IRVIN CLETA HIRAM TAINA MYLES LEROY RENNA ELENE BERTA AISHA NAOMI MARGO DIANE TAMAR JANET CIERA TEDDY THORA MARCO NICOL LOREE ESSIE DANNY JULEE SANTA TAMMY BRYAN ELENA ASHLI DORIS ROXIE KELLY EFFIE MAIDA MINDY LEISA TASHA TUYET HOSEA SOMER LANNY ELTON FLORA CHERI PARIS MATHA LIGIA SHELA DOVIE RONNI MONTE FREDA CARYN SHEBA KARAN BRADY SHALA ZELLA WALLY DANNA KEIKO PERLA FERNE KERRI JACKI BRANT KENNY SACHA ADINA KARRI TARAH DARIA DEBRA ALVIN JINNY LESLI KYLIE TILDA MARCY APRIL VENUS LYMAN SARAH HENRY PALMA GOLDA IVORY JULIA ZELMA ALISA LANCE TESSA PATTY PEARL CHUCK PASTY SHANI DYLAN LUCIA LORNA BELIA KENNA GLADY BULAH MILDA LISHA ABDUL HANNA BORIS KRAIG NELLE NOEMI LOVIE AMADO NAKIA CASSY MANDA JANIE CLAIR IRWIN TARRA HELEN MELIA VILMA CHANG GALEN ELIAS KAYCE KESHA CLARE JEANA MAVIS ROMEO ILEEN PAOLA VESTA WILMA ELVIA FIDEL MARTY ZENIA MINNA RUTHE KAROL HAZEL LAUNA ALLYN MOSES RALPH DIANA CASSI HIEDI ELDON JESUS NIKIA KALYN GERDA CHARA RAMON IESHA RUBIN JUTTA DINAH VELIA JAMAL VELLA DELTA NANCY RAVEN BURMA LEONA TAWNA MYRNA IRENE RIVKA LILLA QUYEN SONIA STARR PENNI LORRI PABLO SOILA AMMIE JANEL ALENA ALONA RENEA MILES JAMEY JUDIE GRAIG DEBBY TAMIE TATUM CARLI SYBIL RUTHA DARLA GLENN WONDA BETTY KEIRA KANDI MELDA MARNA DORLA LILLI GENIE TRISH BILLY TANJA HYMAN SHERY DELMY INDIA RENAE ELINA BERRY BRUCE SONJA IDELL KIARA ROCCO SHIRA ELVIS ROSIE ELOIS KYLEE WILEY BERYL SASHA AGNUS ROGER KYUNG ALENE ALLEN BRYON ROCIO PIPER AFTON SIXTA KATHY SANTO AKIKO LANIE HILDE RENAY WINDY MANDY AUDRY MICHA ANGLA APRYL ZOFIA CLYDE DELLA MILLY DIGNA NUBIA TARYN MAJOR RENEE ISAAC LELAH CASEY MAGDA LUANA VEOLA ESTER MARIN DELMA PAIGE VIKKI ELVIN MASON BROCK STEVE MITZI ZONIA ALYSE ELANA ERVIN TRESA ELMER SANDY TORRI KECIA JOSIE EDGAR MEGAN TRULA JUNKO ELLIE DARIO ARLIE MISHA ANIKA JENNA CHANA LEANA JONAH JOLYN PHUNG JUSTA MARRY CECIL SARAI TRUDI TRACI KEREN ERROL NANCI KYONG LACEY GENIA DARBY KEILA JOLIE OSSIE DAYNA MAXIE OLENE KEVIN JAYNA RONNY REGAN NILDA CELIA GRADY ARDIS ANGLE JODEE JEANE MABEL IZOLA DALIA CHERE CYRUS CIARA BRITT DACIA ELISE BRUNO ARRON KENIA RONNA YOUNG LOGAN FANNY CRAIG DARIN JOSUE MERYL STACY REYES LORIE MARIO PHEBE MARTI LEENA NORAH GREGG ELSIE OLETA FRITZ NEIDA PATSY FONDA LISSA BECKI ERINN DUANE BEATA RUBEN DEVON MAMIE MOLLY OLIVA CHLOE LYNNE BETSY MALIA ELLYN BRETT LEXIE MAGEN SHAWN LEESA CANDY RUFUS SHIRL SUSIE LETTY KAYLA WENDY ALEEN ELDEN OMEGA JOANA MICAH LAILA DEWEY CARRY WANDA LAKIA LUANN SANDI HOLLY FRIDA IRISH PAULA HUONG ADRIA CORIE ANTON RAINA DANTE ABBIE DEANE EDRIS AVERY EMMIE JERRY BUDDY OZELL ANGIE IRENA SELMA NAIDA SUSAN JONAS LOISE VONDA PANSY ASHLY ALDEN EDWIN MAZIE LORIA DAREN ARICA CYNDI WENDI JENNY MARVA NAOMA CAREN CLAUD NOLAN DONYA JAYNE JIMMY OLIVE AMIEE JOSEF HERTA ELIZA LARRY TANDY JACOB JASON WYATT VELDA RHEBA EVITA RUSTY KATHI NELLA ANNIS DAINE LAURE MAIRA RUBIE ANDRA JAYME VANCE ZETTA KARRY DAWNE SHONA ADELE COREY CAYLA JULIE NIGEL CATHY RHETT TEGAN ERICA MALIK TEENA JAMAR CARLO LONDA GEMMA DENIS LYDIA EULAH KIRBY SHANE BONNY DOLLY CLINT SCOTT CHINA LENNY ETHYL INELL CHASE CHERY TOMMY MENDY DIEGO CHAYA SIGNE ETTIE NEOMI EMILE TRENA DEBBI DREMA ROBBI AMADA ALICE MERNA SIBYL MINDA THANH KLARA JANAY ILANA REYNA CINDI ABBEY CAROL ROBBY LOUIE ZOILA SADIE LIVIA FARAH JAMEE SIMON ALINE RHODA SARAN BUFFY NEDRA MIKKI ALITA PEDRO MARIA ROSIA ANISA GENNY JANNA JUNIE TASIA CALEB LAYLA SHERA YVONE PERRY CESAR MARIS JAMES SUNNY EFREN ROYCE RILEY FRANK YETTA LARUE KARON BUNNY ELVIE CARON SUZAN LINDA MACIE KASHA MITCH NELLY LACIE LEOMA STACI ILENE AYAKO TOSHA ANITA KALEY GWENN EMERY EMILY MELVA GINNY ZULMA SONNY RHONA SANDA KARLA SINDY LESHA KARIE KANDY REENA KELLI CYNDY CAMMY EMORY JONNA GAVIN ADELL SUDIE CATHI HEATH AHMED KILEY RONDA DAWNA TISHA DIXIE RICKY MARYA GLORY RYANN TERRA MOSHE JETTA CEOLA EARLE DWAIN TIMMY MIRNA TONYA MARCI".split())


    def __init__(self,nameLength=4):
        if nameLength == 4:
            self.NAME_BASE_DIGITS = self.NAME_BASE_DIGITS4
        elif nameLength == 5:
            self.NAME_BASE_DIGITS = self.NAME_BASE_DIGITS5
        else:
            raise ValueError("nameLength must be one of 4 or 5 only")
        return

    def _convert2nameBase(self, numberIn, to_digits):
        # make an abs integer out of the numberIn
        x = abs(numberIn) 

        # create the result in base 'len(to_digits)'
        outList = list()
        if x == 0:
            outList.append(to_digits[0])
        else:
            while x > 0:
                digit = x % len(to_digits)
                outList.insert(0,to_digits[digit])
                x = int(x // len(to_digits))
        return "-".join(outList)

    def _convert2decimalBase(self, numberIn, from_digits, to_digits):
        # split on dashes
        x = 0
        #print "DBUG: numberIn[{0}]".format(numberIn)
        for digit in numberIn.split("-"):
            #print "DBUG: digit[{0}]".format(digit)
            try:
                x = x * len(from_digits) + from_digits.index(digit)
            except ValueError:
                raise ValueError('invalid name "%s"' % digit)

        # create the result in base 'len(to_digits)'
        if x == 0:
            res = to_digits[0]
        else:
            res = ''
            while x > 0:
                digit = x % len(to_digits)
                res = to_digits[digit] + res
                x = int(x // len(to_digits))
        return res

    def encode(self, numberIn):
        return(self._convert2nameBase(abs(numberIn), self.NAME_BASE_DIGITS))

    def decode(self, nameBaseIn):
        return(self._convert2decimalBase(nameBaseIn, self.NAME_BASE_DIGITS, self.DECIMAL_BASE_DIGITS))



